# Generated by Django 4.0.4 on 2022-06-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('dog_walker', 'DOG WALKER'), ('dog_sitter', 'DOG SITTER'), ('cat_sitter', 'CAT SITTER')], max_length=100),
        ),
    ]
